services: 
  ctf:
    build:
      context: . 
      dockerfile: Dockerfile 
    image: pwnkernel
    container_name: pwnkernel
    stdin_open: true
    tty: true 
    command: /bin/bash 
    volumes: 
      - ctf-data:/

volumes:
  ctf-data:
